In [2]:
!pip install numpy
!pip install pandas
!pip install matplotlib.pyplot
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\oshani\appdata\roaming\python\python312\site-packages (1.26.3)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\oshani\appdata\roaming\python\python312\site-packages (2.2.0)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)
ERROR: No matching distribution found for matplotlib.pyplot

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\oshani\appdata\roaming\python\python312\site-packages (0.13.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from seaborn) (1.26.3)
Requirement already satisfied: pandas>=1.2 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from seaborn) (2.2.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from seaborn) (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from pandas>=1.2->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from pandas>=1.2->seaborn) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
books = pd.read_csv('dataset/Books.csv', sep=";", encoding='latin-1', on_bad_lines='skip')

C:\Users\Oshani\AppData\Local\Temp\ipykernel_13496\3720861349.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('dataset/Books.csv', sep=";", encoding='latin-1', on_bad_lines='skip')

In [9]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [12]:
users = pd.read_csv('dataset/Users.csv', sep=";", encoding='latin-1', on_bad_lines='skip')


users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [13]:
ratings = pd.read_csv('dataset/Ratings.csv', sep=";", encoding='latin-1', on_bad_lines='skip')
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [14]:
books.shape

(271360, 8)

In [15]:
users.shape

(278858, 3)

In [16]:
ratings.shape

(1149780, 3)

In [17]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [18]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
      'Image-URL-L' ]]

In [19]:
books.head(3)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...

In [21]:
new_columns = {
    "Book-Title": "title",
    "Book-Author": "author",
    "Year-Of-Publication": "year",
    "Publisher": "publisher",
    "Image-URL-L": "img_url"
}

books.rename(columns=new_columns, inplace=True)

books.head(3)

,ISBN,title,author,year,publisher,img_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...

In [23]:
new_columns = {

    "User-ID	": "user-id	",
    "Location": "location",
    "Age": "age",
}

users.rename(columns=new_columns, inplace=True)

users.head(5)

   User-ID                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [24]:
new_columns = {

    "User-ID	": "user_id	",
    "Book-Rating": "rating",


}

ratings.rename(columns=new_columns, inplace=True)

ratings.head(5)

   User-ID        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [25]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 6)
(278858, 3)
(1149780, 3)

In [26]:
user_id_counts = ratings['User-ID'].value_counts()


print(user_id_counts)

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [27]:
user_id_counts = ratings['User-ID'].unique().shape
print(user_id_counts)

(105283,)

In [28]:
x = ratings['User-ID'].value_counts()>200


print(x)
x[x].shape

User-ID
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: count, Length: 105283, dtype: bool

(899,)

In [29]:
y=x[x].index

y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='User-ID', length=899)

In [30]:

ratings = ratings[ratings['User-ID'].isin(y)]

print(ratings)

ratings.head(5)

         User-ID        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

      User-ID        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [31]:
ratings.shape

(526356, 3)

In [32]:
books.head(2)

,ISBN,title,author,year,publisher,img_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [33]:
ratings_with_book=ratings.merge(books , on="ISBN")

ratings_with_book

,User-ID,ISBN,rating,title,author,year,publisher,img_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...
487666,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...
487667,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...
487668,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...
487669,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...
487670,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...

In [34]:
ratings_with_book.shape

(487671, 8)

In [35]:
num_ratings =ratings_with_book.groupby('title')['rating'].count().reset_index()
num_ratings.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [36]:
num_ratings.columns = num_ratings.columns.str.strip()

num_ratings.rename(columns={"rating": "num_of_rating"}, inplace=True)


num_ratings.head(5)

                                               title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [37]:
final_rating=ratings_with_book.merge(num_ratings , on="title")

final_rating.head(3)

,User-ID,ISBN,rating,title,author,year,publisher,img_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1

In [38]:
final_rating=final_rating[final_rating['num_of_rating']>=50]


final_rating

,User-ID,ISBN,rating,title,author,year,publisher,img_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79
...,...,...,...,...,...,...,...,...,...
487505,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,84
487506,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,60
487579,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...,59
487618,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,146
487619,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...,53

In [39]:
final_rating.sample(10)

,User-ID,ISBN,rating,title,author,year,publisher,img_url,num_of_rating
352328,203968,0451153553,0,Misery,Stephen King,1988,New Amer Library,http://images.amazon.com/images/P/0451153553.0...,121
196189,112001,0553263226,10,The Bourne Supremacy,Robert Ludlum,1987,Bantam,http://images.amazon.com/images/P/0553263226.0...,56
477326,268932,0446672211,0,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...,183
123495,70052,080410753X,9,The Kitchen God's Wife,Amy Tan,1992,Ivy Books,http://images.amazon.com/images/P/080410753X.0...,111
267361,153718,0312990456,9,One for the Money (A Stephanie Plum Novel),Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312990456.0...,63
465398,262399,0373218400,0,Table For Two,Nora Roberts,2002,Silhouette,http://images.amazon.com/images/P/0373218400.0...,50
52717,28523,0385335881,0,Shopaholic Takes Manhattan (Summer Display Opp...,Sophie Kinsella,2002,Delta,http://images.amazon.com/images/P/0385335881.0...,78
470031,265115,0385335881,9,Shopaholic Takes Manhattan (Summer Display Opp...,Sophie Kinsella,2002,Delta,http://images.amazon.com/images/P/0385335881.0...,78
154813,89602,0786817070,7,"Artemis Fowl (Artemis Fowl, Book 1)",Eoin Colfer,2002,Miramax Kids,http://images.amazon.com/images/P/0786817070.0...,105
333311,194600,080410526X,0,All I Really Need to Know,ROBERT FULGHUM,1989,Ivy Books,http://images.amazon.com/images/P/080410526X.0...,127

In [40]:
final_rating.shape

(61853, 9)

In [41]:
 final_rating.drop_duplicates(['User-ID', 'title'], inplace=True)

In [42]:
final_rating.shape

(59850, 9)

In [43]:
final_rating

,User-ID,ISBN,rating,title,author,year,publisher,img_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79
...,...,...,...,...,...,...,...,...,...
487505,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,84
487506,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,60
487579,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...,59
487618,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,146
487619,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...,53

In [45]:
book_pivot=final_rating.pivot_table(columns='User-ID',index='title',values='rating')

book_pivot

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
book_pivot.fillna(0,inplace=True)

book_pivot

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
!pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Collecting scipy
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/f3/31/91a2a3c5eb85d2bfa86d7c98f2df5d77dcdefb3d80ca9f9037ad04393acf/scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata
  Downloading scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.4 kB 682.7 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/60.4 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 643.6 kB/s eta 0:00:00
Requirement already satisfied: numpy<1.29.0,>=1.22.4 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from scipy) (1.26.3)
Downloading scipy-1.12.0-cp312-cp312-win_amd64.whl (45.8 MB)
   ---------------------------------------- 0.0/45.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/45.8 MB 1.7 MB/s eta 0:00:28
   ---------------------------------------- 0.2/45.8 MB 2.1 MB/s eta 0:00:22
   ---------------------------------------- 0.4/45.8 MB 2.9 MB/s eta 0:00:16
    --------------------------------------- 0.6/45.8 MB 3.4 MB/s eta 0:00:14
    --------------------------------------- 0.9/45.8 MB 3.6 MB/s eta 0:00:13
    --------------------------------------- 1.1/45.8 MB 3.9 MB/s eta 0:00:12
   - -------------------------------------- 1.3/45.8 MB 4.2 MB/s eta 0:00:11
   - -------------------------------------- 1.6/45.8 MB 4.3 MB/s eta 0:00:11
   - -------------------------------------- 1.8/45.8 MB 4.3 MB/s eta 0:00:11
   - -------------------------------------- 2.0/45.8 MB 4.5 MB/s eta 0:00:10
   -- ------------------------------------- 2.3/45.8 MB 4.5 MB/s eta 0:00:10
   -- ------------------------------------- 2.6/45.8 MB 4.6 MB/s eta 0:00:10
   -- ------------------------------------- 2.8/45.8 MB 4.6 MB/s eta 0:00:10
   -- ------------------------------------- 3.1/45.8 MB 4.6 MB/s eta 0:00:10
   -- ------------------------------------- 3.3/45.8 MB 4.6 MB/s eta 0:00:10
   --- ------------------------------------ 3.5/45.8 MB 4.7 MB/s eta 0:00:09
   --- ------------------------------------ 3.8/45.8 MB 4.8 MB/s eta 0:00:09
   --- ------------------------------------ 4.0/45.8 MB 4.8 MB/s eta 0:00:09
   --- ------------------------------------ 4.3/45.8 MB 4.9 MB/s eta 0:00:09
   --- ------------------------------------ 4.6/45.8 MB 4.9 MB/s eta 0:00:09
   ---- ----------------------------------- 4.8/45.8 MB 5.0 MB/s eta 0:00:09
   ---- ----------------------------------- 5.1/45.8 MB 5.0 MB/s eta 0:00:09
   ---- ----------------------------------- 5.4/45.8 MB 5.0 MB/s eta 0:00:09
   ---- ----------------------------------- 5.6/45.8 MB 5.1 MB/s eta 0:00:08
   ----- ---------------------------------- 5.8/45.8 MB 5.0 MB/s eta 0:00:08
   ----- ---------------------------------- 6.0/45.8 MB 5.0 MB/s eta 0:00:08
   ----- ---------------------------------- 6.3/45.8 MB 5.0 MB/s eta 0:00:08
   ----- ---------------------------------- 6.5/45.8 MB 5.0 MB/s eta 0:00:08
   ----- ---------------------------------- 6.8/45.8 MB 5.0 MB/s eta 0:00:08
   ------ --------------------------------- 7.0/45.8 MB 5.0 MB/s eta 0:00:08
   ------ --------------------------------- 7.2/45.8 MB 5.0 MB/s eta 0:00:08
   ------ --------------------------------- 7.5/45.8 MB 5.0 MB/s eta 0:00:08
   ------ --------------------------------- 7.7/45.8 MB 5.0 MB/s eta 0:00:08
   ------ --------------------------------- 8.0/45.8 MB 5.1 MB/s eta 0:00:08
   ------- -------------------------------- 8.2/45.8 MB 5.1 MB/s eta 0:00:08
   ------- -------------------------------- 8.4/45.8 MB 5.0 MB/s eta 0:00:08
   ------- -------------------------------- 8.7/45.8 MB 5.0 MB/s eta 0:00:08
   ------- -------------------------------- 8.9/45.8 MB 5.0 MB/s eta 0:00:08
   ------- -------------------------------- 9.1/45.8 MB 5.0 MB/s eta 0:00:08
   -------- ------------------------------- 9.3/45.8 MB 5.0 MB/s eta 0:00:08
   -------- ------------------------------- 9.6/45.8 MB 5.0 MB/s eta 0:00:08
   -------- ------------------------------- 9.7/45.8 MB 5.0 MB/s eta 0:00:08
   -------- ------------------------------- 10.0/45.8 MB 5.0 MB/s eta 0:00:08
   -------- ------------------------------- 10.2/45.8 MB 5.0 MB/s eta 0:00:08
   --------- ------------------------------ 10.5/45.8 MB 5.2 MB/s eta 0:00:07
   --------- ------------------------------ 10.8/45.8 MB 5.2 MB/s eta 0:00:07
   --------- ------------------------------ 11.1/45.8 MB 5.2 MB/s eta 0:00:07
   --------- ------------------------------ 11.4/45.8 MB 5.2 MB/s eta 0:00:07
   ---------- ----------------------------- 11.6/45.8 MB 5.2 MB/s eta 0:00:07
   ---------- ----------------------------- 12.0/45.8 MB 5.3 MB/s eta 0:00:07
   ---------- ----------------------------- 12.2/45.8 MB 5.3 MB/s eta 0:00:07
   ---------- ----------------------------- 12.5/45.8 MB 5.3 MB/s eta 0:00:07
   ----------- ---------------------------- 12.7/45.8 MB 5.3 MB/s eta 0:00:07
   ----------- ---------------------------- 13.0/45.8 MB 5.3 MB/s eta 0:00:07
   ----------- ---------------------------- 13.3/45.8 MB 5.3 MB/s eta 0:00:07
   ----------- ---------------------------- 13.5/45.8 MB 5.4 MB/s eta 0:00:07
   ------------ --------------------------- 13.8/45.8 MB 5.4 MB/s eta 0:00:06
   ------------ --------------------------- 14.1/45.8 MB 5.4 MB/s eta 0:00:06
   ------------ --------------------------- 14.3/45.8 MB 5.4 MB/s eta 0:00:06
   ------------ --------------------------- 14.6/45.8 MB 5.4 MB/s eta 0:00:06
   ------------ --------------------------- 14.8/45.8 MB 5.4 MB/s eta 0:00:06
   ------------- -------------------------- 15.1/45.8 MB 5.4 MB/s eta 0:00:06
   ------------- -------------------------- 15.4/45.8 MB 5.4 MB/s eta 0:00:06
   ------------- -------------------------- 15.6/45.8 MB 5.4 MB/s eta 0:00:06
   ------------- -------------------------- 15.9/45.8 MB 5.4 MB/s eta 0:00:06
   -------------- ------------------------- 16.2/45.8 MB 5.5 MB/s eta 0:00:06
   -------------- ------------------------- 16.5/45.8 MB 5.5 MB/s eta 0:00:06
   -------------- ------------------------- 16.8/45.8 MB 5.5 MB/s eta 0:00:06
   --------------- ------------------------ 17.2/45.8 MB 5.5 MB/s eta 0:00:06
   --------------- ------------------------ 17.5/45.8 MB 5.6 MB/s eta 0:00:06
   --------------- ------------------------ 17.8/45.8 MB 5.6 MB/s eta 0:00:06
   --------------- ------------------------ 18.1/45.8 MB 5.5 MB/s eta 0:00:06
   ---------------- ----------------------- 18.4/45.8 MB 5.5 MB/s eta 0:00:05
   ---------------- ----------------------- 18.6/45.8 MB 5.6 MB/s eta 0:00:05
   ---------------- ----------------------- 18.8/45.8 MB 5.6 MB/s eta 0:00:05
   ---------------- ----------------------- 19.1/45.8 MB 5.6 MB/s eta 0:00:05
   ---------------- ----------------------- 19.3/45.8 MB 5.6 MB/s eta 0:00:05
   ----------------- ---------------------- 19.6/45.8 MB 5.7 MB/s eta 0:00:05
   ----------------- ---------------------- 19.9/45.8 MB 5.8 MB/s eta 0:00:05
   ----------------- ---------------------- 20.1/45.8 MB 5.7 MB/s eta 0:00:05
   ----------------- ---------------------- 20.4/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------ --------------------- 20.6/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------ --------------------- 20.9/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------ --------------------- 21.2/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------ --------------------- 21.4/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------ --------------------- 21.7/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------- -------------------- 22.1/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------- -------------------- 22.3/45.8 MB 5.7 MB/s eta 0:00:05
   ------------------- -------------------- 22.7/45.8 MB 5.7 MB/s eta 0:00:05
   -------------------- ------------------- 23.0/45.8 MB 5.7 MB/s eta 0:00:04
   -------------------- ------------------- 23.2/45.8 MB 5.7 MB/s eta 0:00:04
   -------------------- ------------------- 23.5/45.8 MB 5.7 MB/s eta 0:00:04
   -------------------- ------------------- 23.7/45.8 MB 5.6 MB/s eta 0:00:04
   -------------------- ------------------- 24.0/45.8 MB 5.6 MB/s eta 0:00:04
   --------------------- ------------------ 24.3/45.8 MB 5.6 MB/s eta 0:00:04
   --------------------- ------------------ 24.6/45.8 MB 5.6 MB/s eta 0:00:04
   --------------------- ------------------ 24.8/45.8 MB 5.6 MB/s eta 0:00:04
   --------------------- ------------------ 25.1/45.8 MB 5.6 MB/s eta 0:00:04
   ---------------------- ----------------- 25.4/45.8 MB 5.6 MB/s eta 0:00:04
   ---------------------- ----------------- 25.6/45.8 MB 5.6 MB/s eta 0:00:04
   ---------------------- ----------------- 25.8/45.8 MB 5.6 MB/s eta 0:00:04
   ---------------------- ----------------- 26.1/45.8 MB 5.6 MB/s eta 0:00:04
   ----------------------- ---------------- 26.3/45.8 MB 5.5 MB/s eta 0:00:04
   ----------------------- ---------------- 26.6/45.8 MB 5.5 MB/s eta 0:00:04
   ----------------------- ---------------- 26.8/45.8 MB 5.5 MB/s eta 0:00:04
   ----------------------- ---------------- 27.0/45.8 MB 5.5 MB/s eta 0:00:04
   ----------------------- ---------------- 27.3/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------ --------------- 27.6/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------ --------------- 27.8/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------ --------------- 28.1/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------ --------------- 28.4/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------ --------------- 28.6/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------- -------------- 28.9/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------- -------------- 29.2/45.8 MB 5.5 MB/s eta 0:00:04
   ------------------------- -------------- 29.4/45.8 MB 5.5 MB/s eta 0:00:03
   ------------------------- -------------- 29.7/45.8 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 29.9/45.8 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 30.2/45.8 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 30.4/45.8 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 30.7/45.8 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 30.9/45.8 MB 5.5 MB/s eta 0:00:03
   --------------------------- ------------ 31.2/45.8 MB 5.5 MB/s eta 0:00:03
   --------------------------- ------------ 31.4/45.8 MB 5.5 MB/s eta 0:00:03
   --------------------------- ------------ 31.6/45.8 MB 5.4 MB/s eta 0:00:03
   --------------------------- ------------ 31.9/45.8 MB 5.4 MB/s eta 0:00:03
   ---------------------------- ----------- 32.2/45.8 MB 5.4 MB/s eta 0:00:03
   ---------------------------- ----------- 32.4/45.8 MB 5.4 MB/s eta 0:00:03
   ---------------------------- ----------- 32.7/45.8 MB 5.4 MB/s eta 0:00:03
   ---------------------------- ----------- 32.9/45.8 MB 5.4 MB/s eta 0:00:03
   ---------------------------- ----------- 33.2/45.8 MB 5.4 MB/s eta 0:00:03
   ----------------------------- ---------- 33.4/45.8 MB 5.4 MB/s eta 0:00:03
   ----------------------------- ---------- 33.8/45.8 MB 5.4 MB/s eta 0:00:03
   ----------------------------- ---------- 34.0/45.8 MB 5.4 MB/s eta 0:00:03
   ----------------------------- ---------- 34.2/45.8 MB 5.4 MB/s eta 0:00:03
   ------------------------------ --------- 34.5/45.8 MB 5.4 MB/s eta 0:00:03
   ------------------------------ --------- 34.8/45.8 MB 5.4 MB/s eta 0:00:03
   ------------------------------ --------- 35.0/45.8 MB 5.5 MB/s eta 0:00:02
   ------------------------------ --------- 35.3/45.8 MB 5.4 MB/s eta 0:00:02
   ------------------------------ --------- 35.5/45.8 MB 5.4 MB/s eta 0:00:02
   ------------------------------- -------- 35.8/45.8 MB 5.4 MB/s eta 0:00:02
   ------------------------------- -------- 36.0/45.8 MB 5.4 MB/s eta 0:00:02
   ------------------------------- -------- 36.3/45.8 MB 5.4 MB/s eta 0:00:02
   ------------------------------- -------- 36.6/45.8 MB 5.4 MB/s eta 0:00:02
   -------------------------------- ------- 36.8/45.8 MB 5.4 MB/s eta 0:00:02
   -------------------------------- ------- 37.0/45.8 MB 5.4 MB/s eta 0:00:02
   -------------------------------- ------- 37.3/45.8 MB 5.4 MB/s eta 0:00:02
   -------------------------------- ------- 37.5/45.8 MB 5.4 MB/s eta 0:00:02
   -------------------------------- ------- 37.7/45.8 MB 5.4 MB/s eta 0:00:02
   --------------------------------- ------ 38.0/45.8 MB 5.4 MB/s eta 0:00:02
   --------------------------------- ------ 38.2/45.8 MB 5.4 MB/s eta 0:00:02
   --------------------------------- ------ 38.5/45.8 MB 5.3 MB/s eta 0:00:02
   --------------------------------- ------ 38.7/45.8 MB 5.3 MB/s eta 0:00:02
   --------------------------------- ------ 38.9/45.8 MB 5.3 MB/s eta 0:00:02
   ---------------------------------- ----- 39.2/45.8 MB 5.3 MB/s eta 0:00:02
   ---------------------------------- ----- 39.4/45.8 MB 5.3 MB/s eta 0:00:02
   ---------------------------------- ----- 39.6/45.8 MB 5.2 MB/s eta 0:00:02
   ---------------------------------- ----- 39.9/45.8 MB 5.2 MB/s eta 0:00:02
   ----------------------------------- ---- 40.1/45.8 MB 5.3 MB/s eta 0:00:02
   ----------------------------------- ---- 40.3/45.8 MB 5.3 MB/s eta 0:00:02
   ----------------------------------- ---- 40.6/45.8 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 40.9/45.8 MB 5.3 MB/s eta 0:00:01
   ----------------------------------- ---- 41.1/45.8 MB 5.3 MB/s eta 0:00:01
   ------------------------------------ --- 41.4/45.8 MB 5.3 MB/s eta 0:00:01
   ------------------------------------ --- 41.7/45.8 MB 5.3 MB/s eta 0:00:01
   ------------------------------------ --- 41.9/45.8 MB 5.4 MB/s eta 0:00:01
   ------------------------------------ --- 42.2/45.8 MB 5.4 MB/s eta 0:00:01
   ------------------------------------- -- 42.4/45.8 MB 5.4 MB/s eta 0:00:01
   ------------------------------------- -- 42.7/45.8 MB 5.4 MB/s eta 0:00:01
   ------------------------------------- -- 43.0/45.8 MB 5.4 MB/s eta 0:00:01
   ------------------------------------- -- 43.1/45.8 MB 5.4 MB/s eta 0:00:01
   ------------------------------------- -- 43.3/45.8 MB 5.3 MB/s eta 0:00:01
   ------------------------------------- -- 43.5/45.8 MB 5.3 MB/s eta 0:00:01
   -------------------------------------- - 43.8/45.8 MB 5.3 MB/s eta 0:00:01
   -------------------------------------- - 44.0/45.8 MB 5.3 MB/s eta 0:00:01
   -------------------------------------- - 44.3/45.8 MB 5.3 MB/s eta 0:00:01
   -------------------------------------- - 44.5/45.8 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  44.8/45.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  45.0/45.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  45.3/45.8 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  45.5/45.8 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 45.8/45.8 MB 4.8 MB/s eta 0:00:00
Installing collected packages: scipy
Successfully installed scipy-1.12.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [51]:
from scipy.sparse import csr_matrix

In [52]:
book_sparse=csr_matrix(book_pivot)

In [53]:
book_sparse

<742x888 sparse matrix of type '<class 'numpy.float64'>'
	with 14961 stored elements in Compressed Sparse Row format>

In [55]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/f6/28/b569523552a11b49dc4d33952f43dedb23792fe8ce2f2151d070d615861a/scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl.metadata
  Downloading scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.26.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\oshani\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.12.0)
Collecting joblib>=1.2.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Downloading scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 1.4 MB/s eta 0:00:08
   ---------------------------------------- 0.1/10.6 MB 991.0 kB/s eta 0:00:11
    --------------------------------------- 0.2/10.6 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.4/10.6 MB 2.1 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/10.6 MB 2.6 MB/s eta 0:00:04
   --- ------------------------------------ 0.8/10.6 MB 3.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.1/10.6 MB 3.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/10.6 MB 3.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.5/10.6 MB 3.8 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/10.6 MB 3.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/10.6 MB 4.1 MB/s eta 0:00:03
   -------- ------------------------------- 2.3/10.6 MB 4.2 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/10.6 MB 4.4 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/10.6 MB 4.5 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/10.6 MB 4.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/10.6 MB 4.6 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/10.6 MB 4.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/10.6 MB 4.8 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/10.6 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/10.6 MB 4.9 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/10.6 MB 5.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/10.6 MB 4.9 MB/s eta 0:00:02
   ------------------- -------------------- 5.3/10.6 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 5.5/10.6 MB 5.1 MB/s eta 0:00:01
   --------------------- ------------------ 5.8/10.6 MB 5.1 MB/s eta 0:00:01
   ---------------------- ----------------- 6.1/10.6 MB 5.1 MB/s eta 0:00:01
   ----------------------- ---------------- 6.3/10.6 MB 5.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.5/10.6 MB 5.1 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.6 MB 5.1 MB/s eta 0:00:01
   -------------------------- ------------- 7.0/10.6 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 7.2/10.6 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 7.5/10.6 MB 5.1 MB/s eta 0:00:01
   ----------------------------- ---------- 7.7/10.6 MB 5.1 MB/s eta 0:00:01
   ------------------------------ --------- 8.0/10.6 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.3/10.6 MB 5.0 MB/s eta 0:00:01
   -------------------------------- ------- 8.6/10.6 MB 5.1 MB/s eta 0:00:01
   --------------------------------- ------ 8.8/10.6 MB 5.1 MB/s eta 0:00:01
   ---------------------------------- ----- 9.0/10.6 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.3/10.6 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.5/10.6 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 9.8/10.6 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.0/10.6 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 10.3/10.6 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 3.7 MB/s eta 0:00:00
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ---------------------------------------- 0.0/302.2 kB ? eta -:--:--
   -------------------------------- ------- 245.8/302.2 kB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 302.2/302.2 kB 6.2 MB/s eta 0:00:00
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.3.2 scikit-learn-1.4.0 threadpoolctl-3.2.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')

In [57]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [58]:
distance , suggestion =model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [59]:
distance

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [60]:
suggestion

array([[237, 238, 240, 241, 184, 536]], dtype=int64)

In [61]:
for i in range(len(suggestion)):
  print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='title')

In [62]:
book_pivot.index[3]

'4 Blondes'

In [63]:
book_pivot.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=742)

In [64]:
books_name=book_pivot.index

In [66]:
import pickle
pickle.dump(model, open('artifacts/model.pkl','wb'))
pickle.dump(books_name, open('artifacts/books_name.pkl','wb'))
pickle.dump(final_rating, open('artifacts/final_rating.pkl','wb'))
pickle.dump(book_pivot, open('artifacts/book_pivot.pkl','wb'))

In [68]:
def recommend_book(book_name):
    book_id=np.where(book_pivot.index==book_name)[0][0]
    distance , suggestion =model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)

    for i in range(len(suggestion)):
        books=book_pivot.index[suggestion[i]]
        for j in books:
            print(j)

In [70]:
book_name="A Bend in the Road"
recommend_book(book_name)

A Bend in the Road
Exclusive
The Cradle Will Fall
No Safe Place
Family Album
Last Man Standing